name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_VPN_KEY }}

      - name: Add VPS to known_hosts
        run: |
          ssh-keyscan -H 91.214.191.172 >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh ubuntu@91.214.191.172 "cd /home/ubuntu/docker/apps/api-express && git pull origin main"
