name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.2.2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_VPN_KEY }}

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 91.214.191.172 >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts  # Debugging output to check known_hosts contents

      - name: Check SSH agent status
        run: ssh-add -l

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@91.214.191.172 <<EOF
          cd /home/ubuntu/docker/apps/api-express
          git pull origin main
          EOF
         
