name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.2

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 91.214.191.172 >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@91.214.191.172 <<EOF
          cd /home/ubuntu/docker/apps/api-express
          git pull origin main
          # Add any additional deployment steps here, e.g., restarting services
          EOF